name: CI

on:
  push:
    branches: ["main", "staged", "dev"]
  pull_request:
    branches: ["main", "staged", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run ESLint, Stylelint and Prettier check
      - name: Run ESLint
        run: npm run lint

      # - name: Run tests
      #   run: npm test

      # Step 5: Build the project
      - name: Build
        run: npm run build

      # Optional Deployment Step
      # - name: Deploy
      #   run: |
      #     echo "Deploying to production server..."
      #     # Add your deployment script here
      #   env:
      #     DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_KEY }}
